refactor ui tests
StepicOrg/stepik-ios pull request #1148
Opened 2022-05-26 08:23 UTC by annafalileeva

**YouTrack task**: [#APPS-3640](https://vyahhi.myjetbrains.com/youtrack/issue/APPS-3640)

**Description**:
refactor ui tests

2022-05-26 12:59 UTC, ivan-magda requested changes
@annafalileeva 

Ты не против, если бы я сделал shared файл между приложением и UI тестами,  где были бы описаны все константы accessibility идентификаторов. Кажется так будет меньше шанс ошибиться и нужно будет указать строку идентификатора только в одном месте. Пример как будет выглядеть использование такого API:

в приложении
```swift
self.actionButton.accessibilityIdentifier = AccessibilityIdentifiers.loginButton
```

в UI тестах
```swift
app.buttons[AccessibilityIdentifiers.loginButton]
```

Ещё у нас имеется линтер и автоматические исправления в соответствии code style.
1. Запусти  автоматические исправления в командной строке `./autocorrect.sh StepicUITests`
2. Запусти линтер, чтобы увидеть замечания в командной строке `./lint.sh StepicUITests`. Если не удастся исправить все замечания, то я пофиксю.
3. Ознакомься с [Code Style Stepik](https://hackmd.io/@H3B95HjrQPOVNUczyiRhxw/SJMh5GsrX?type=view#Stepik-Code-Style-Guide).

2022-05-26 12:59 UTC, ivan-magda commented on Stepic/Legacy/Controllers/Onboarding/Onboarding.storyboard
> +                                <userDefinedRuntimeAttribute type="string" keyPath="accessibilityIdentifier" value="closeOnbordingButton"/>
Давай будем все accessibility идентификаторы указывать в коде, если здесь не понятно как это сделать, то я могу.

2022-05-26 12:59 UTC, ivan-magda commented on Stepic/Legacy/Controllers/Onboarding/OnboardingPageView/OnboardingPageView.xib
> +                        <userDefinedRuntimeAttribute type="string" keyPath="accessibilityIdentifier" value="nextButton"/>
Также указать идентификатор в коде

2022-05-26 12:59 UTC, ivan-magda commented on StepicUITests/Pages/AuthScreen.swift
> +//
Заголовки для файлов не нужно указывать. Во всех созданных файлах заголовки нужно удалить.

2022-05-26 12:59 UTC, ivan-magda commented on StepicUITests/Pages/LogInScreen.swift
> +    func fillUserInfo(email: String, password: String) -> LogInScreen {
Я вижу, что благодаря тому что эта функция возвращает "себя", то получается удобно организовать цепочку вызовов, как у тебя:
```swift
logInScreen
    .fillUserInfo(email: email, password: ts)
    .clickLogIn()
```

Но хочется единообразия в API "Экрана":
1. Пускай все функции имеют возвращаемое значение на `Self` и тогда мы точно будем знать, что при вызове любой функции "Экрана" мы имеем возможность организовать цепочку вызовов.
2. Пускай все функции "Экрана" не будут иметь возвращаемого значения, тогда пример выше трансформируется в
```swift
logInScreen.fillUserInfo(email: email, password: ts)
logInScreen.clickLogIn()
```

P.S.
Этот комментарий относится не только к этому классу, но и ко всем Экранам.

2022-05-26 12:59 UTC, ivan-magda commented on StepicUITests/Tests/BaseTest.swift
> +//    }
Если закомментированный код не нужен, то можно удалить.

2022-05-26 12:59 UTC, ivan-magda commented on StepicUITests/Tests/CatalogTests.swift
> +    }
Наверное override этого метода не нужен, т.к. и так вызовется реализация базового класса?

2022-05-26 15:18 UTC, annafalileeva commented on Stepic/Legacy/Controllers/Onboarding/Onboarding.storyboard
> +                                <userDefinedRuntimeAttribute type="string" keyPath="accessibilityIdentifier" value="closeOnbordingButton"/>
Да, хорошо

2022-05-26 15:18 UTC, annafalileeva commented on Stepic/Legacy/Controllers/Onboarding/Onboarding.storyboard
> +                                <userDefinedRuntimeAttribute type="string" keyPath="accessibilityIdentifier" value="closeOnbordingButton"/>
>Ты не против, если бы я сделал shared файл между приложением и UI тестами
Не против

2022-05-27 03:50 UTC, ivan-magda commented on Stepic/Legacy/Controllers/Onboarding/Onboarding.storyboard
> +                                <userDefinedRuntimeAttribute type="string" keyPath="accessibilityIdentifier" value="closeOnbordingButton"/>
@annafalileeva добавил `StepicUITests/Sources/AccessibilityIdentifiers.swift`

2022-05-27 03:50 UTC, ivan-magda commented on Stepic/Legacy/Controllers/Onboarding/OnboardingPageView/OnboardingPageView.xib
> +                        <userDefinedRuntimeAttribute type="string" keyPath="accessibilityIdentifier" value="nextButton"/>
Я это исправил

2022-06-07 09:55 UTC, annafalileeva commented on StepicUITests/Tests/CatalogTests.swift
> +    }
Да, не нужен, убрала

2022-06-07 09:57 UTC, annafalileeva commented on StepicUITests/Pages/LogInScreen.swift
> +    func fillUserInfo(email: String, password: String) -> LogInScreen {
Убрала цепочку пока, она не так много используется, а без нее функции проще
Если в будущем увидим, что их много где можно использовать, то добавим

2022-06-07 15:10 UTC, ivan-magda approved these changes
@annafalileeva все ОК 👍 

Я еще немножко причесал тесты c17d9e685dc83c8976a5561934e3ea2d13a11ae6 и весь код поместил в папку `Sources`.

2022-06-07 15:11 UTC, merged