Uitests/add registration tests
StepicOrg/stepik-ios pull request #935
Opened 2021-03-24 00:28 UTC by CKuB

Add UI tests: [#SQA-809](https://vyahhi.myjetbrains.com/youtrack/issue/SQA-809)

**Description**:
Add pageobject and UI tests for registration, login and logout

2021-03-24 08:42 UTC, ivan-magda commented
Выполни команду `./autocorrect.sh StepicUITests` и пушни изменения.

2021-03-24 10:52 UTC, CKuB commented
> Выполни команду `./autocorrect.sh StepicUITests` и пушни изменения.

Готово.

2021-03-24 15:09 UTC, ivan-magda requested changes
У меня тесты постоянно фейлятся на этапе вставки текста из буфера обмена (`Common.pasteTextFieldText`) в email/password поля.

Хочется, чтобы новые тесты были зелёными.

2021-04-16 19:17 UTC, ivan-magda approved these changes

2021-04-16 19:18 UTC, merged